### ISSUE TITLE
SBML TestSuite failing test semantic/01488/01488 `java.lang.ArithmeticException: arcsech(0) undefined`

### ISSUE THREAD

**Issue by matthiaskoenig** [draeger-lab/SBSCL#38]
Test fails due to: `java.lang.ArithmeticException: arcsech(0) undefined`
```
java.lang.ArithmeticException: arcsech(0) undefined

	at org.sbml.jsbml.util.Maths.arcsech(Maths.java:145)
	at org.simulator.sbml.astnode.ASTNodeInterpreter.arcsech(ASTNodeInterpreter.java:727)
	at org.simulator.sbml.astnode.ASTNodeValue.computeDoubleValue(ASTNodeValue.java:408)
	at org.simulator.sbml.astnode.ASTNodeValue.compileDouble(ASTNodeValue.java:284)
	at org.simulator.sbml.astnode.ASTNodeInterpreter.functionDouble(ASTNodeInterpreter.java:192)
	at org.simulator.sbml.astnode.FunctionValue.computeDoubleValue(FunctionValue.java:121)
	at org.simulator.sbml.astnode.ASTNodeValue.compileDouble(ASTNodeValue.java:284)
	at org.simulator.sbml.astnode.ASTNodeInterpreter.functionDouble(ASTNodeInterpreter.java:190)
	at org.simulator.sbml.astnode.FunctionValue.computeDoubleValue(FunctionValue.java:121)
	at org.simulator.sbml.astnode.ASTNodeValue.compileDouble(ASTNodeValue.java:284)
	at org.simulator.sbml.astnode.RuleValue.processAssignmentVariable(RuleValue.java:128)
	at org.simulator.sbml.astnode.AssignmentRuleValue.processRule(AssignmentRuleValue.java:102)
	at org.simulator.sbml.SBMLinterpreter.processRules(SBMLinterpreter.java:2511)
	at org.simulator.sbml.SBMLinterpreter.init(SBMLinterpreter.java:1475)
	at org.simulator.sbml.SBMLinterpreter.<init>(SBMLinterpreter.java:564)
	at org.simulator.sbml.SBMLTestSuiteTest.testModel(SBMLTestSuiteTest.java:144)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by hemilpanchiwala** [comment]
@matthiaskoenig, resolved the error in the commit linked above!

**Comment by hemilpanchiwala** [comment]
@matthiaskoenig, this issue is resolved now so, we can close it!

**Comment by draeger** [comment]
@hemilpanchiwala when stating that a problem is solved, could you please directly provide the link to the commit? Thanks!

**Comment by hemilpanchiwala** [comment]
> @hemilpanchiwala when stating that a problem is solved, could you please directly provide the link to the commit? Thanks!

@draeger, as we discussed in the last meeting, it was solved without any change so maybe I did some mistake before in testing. So, no commit to link here.

**Comment by draeger** [comment]
Ok, should we close the issue now?
